# Project: CalculadoraCpp
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = CalculdoraCpp.o
LINKOBJ  = CalculdoraCpp.o
LIBS     = -L"D:/prog and/office/Dev-Cpp/TDM-GCC-64/lib" -L"D:/prog and/office/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"D:/prog and/office/Dev-Cpp/TDM-GCC-64/include" -I"D:/prog and/office/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/prog and/office/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/prog and/office/Dev-Cpp/TDM-GCC-64/include" -I"D:/prog and/office/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/prog and/office/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/prog and/office/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = CalculadoraCpp.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\prog and\office\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

CalculdoraCpp.o: CalculdoraCpp.cpp
	$(CPP) -c CalculdoraCpp.cpp -o CalculdoraCpp.o $(CXXFLAGS)
